### ISSUE TITLE
where is the res101?

### ISSUE THREAD

**Issue by HHY-ZJU** [cetinsamet/attribute-label-embedding#1]
i try to run this code, but i get an error:

`FileNotFoundError: [Errno 2] No such file or directory: 'data/AWA2P/features/res101/trainValFeatures.mat'`

so i wonder where is it? @cetinsamet thank u so much if you can help me!

**Comment by cetinsamet** [comment]
Hi @HHY-ZJU,

I have just uploaded the res101/ content. 
Best.
